name: Provision Fabric Data Platform
on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@v3

    # Login to Azure
    - uses: azure/login@v1
      with:
        creds: >
          {
            "clientId": "${{ secrets.ACTION_SPN_CLIENTID }}",
            "clientSecret": "${{ secrets.ACTION_SPN_SECRET }}",
            "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.TENANT_ID }}"
          }

    # Debug secrets (for å verifisere de er injisert riktig)
    - name: Debug Secrets
      run: |
        echo "Client ID: ${{ secrets.ACTION_SPN_CLIENTID }}"
        echo "Tenant ID: ${{ secrets.TENANT_ID }}"
        echo "Subscription ID: ${{ secrets.SUBSCRIPTION_ID }}"
        # Ikke echo client secret!

    # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: northeurope
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        template: iac/bicep/main.bicep
        failOnStdErr: false
