name: Azure Bicep Deployment

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - '**.bicep'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ACTION_SPN_CLIENTID }}","clientSecret":"${{ secrets.ACTION_SPN_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          
      - name: Install Bicep CLI
        run: az bicep install

      - name: Build Bicep Template
        run: az bicep build --file iac/bicep/main.bicep

      - name: Validate Bicep Template
        run: |
          DEPLOYMENT_NAME="validate-$(date +%s)"
          az deployment sub validate \
            --name $DEPLOYMENT_NAME \
            --location westus \
            --template-file iac/bicep/main.bicep \
            --no-prompt \
            --debug
      
      - name: Deploy Bicep Template
        run: |
          DEPLOYMENT_NAME="deploy-$(date +%s)"
          az deployment sub create \
            --name $DEPLOYMENT_NAME \
            --location westus \
            --template-file iac/bicep/main.bicep \
            --no-prompt \
            --debug


