name: Azure Bicep Deployment

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - '**.bicep'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep CLI
        run: az bicep install

      - name: Build Bicep Template
        run: az bicep build --file iac/bicep/main.bicep

      - name: Validate Bicep Template
        run: |
          az deployment sub validate \
            --location westus \
            --template-file iac/bicep/main.bicep \
            --parameters @iac/bicep/parameters.json \
            --debug

      - name: Deploy Bicep Template
        run: |
          az deployment sub create \
            --location westus \
            --template-file iac/bicep/main.bicep \
            --parameters @iac/bicep/parameters.json \
            --debug
